#!/usr/bin/env php
<?php
/*
 * This file is part of Flarum.
 *
 * (c) Toby Zerner <toby.zerner@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

define('FLARUM_START', microtime(true));

require 'vendor/autoload.php';

$server = new Flarum\Console\Server(__DIR__);

$server->listen();
