#!/usr/bin/env php
<?php

$app = require_once __DIR__.'/bootstrap.php';

$console = new \Symfony\Component\Console\Application('Flarum', '0.1.0-beta');

$console->add(new \Flarum\Install\Console\InstallCommand($app));
$console->add(new \Flarum\Console\UpgradeCommand($app));
$console->add(new \Flarum\Console\GenerateExtensionCommand($app));

exit($console->run());
