#!/usr/bin/env php
<?php

$app = require_once __DIR__.'/bootstrap.php';

$app->instance('type', '');
$app->register('Flarum\Support\Extensions\ExtensionsServiceProvider');

$kernel = $app->make('Illuminate\Contracts\Console\Kernel');

$status = $kernel->handle(
	$input = new Symfony\Component\Console\Input\ArgvInput,
	new Symfony\Component\Console\Output\ConsoleOutput
);

$kernel->terminate($input, $status);

exit($status);
